export interface VoicePreset {
  id: string;
  name: string;
  accent: string;
  language: string;
  gender: 'male' | 'female' | 'neutral';
  description: string;
  elevenlabsVoiceId: string;
  isPremium: boolean;
}

export const voicePresets: VoicePreset[] = [
  // English (International)
  {
    id: 'en-us-female-1',
    name: 'Sarah',
    accent: 'American',
    language: 'English (US)',
    gender: 'female',
    description: 'Warm, professional American female voice',
    elevenlabsVoiceId: 'EXAVITQu4vr4xnSDxUw',
    isPremium: false,
  },
  {
    id: 'en-us-male-1',
    name: 'James',
    accent: 'American',
    language: 'English (US)',
    gender: 'male',
    description: 'Clear, authoritative American male voice',
    elevenlabsVoiceId: 'CwhRBWXzGAH1IwTByfo',
    isPremium: false,
  },
  {
    id: 'en-uk-female-1',
    name: 'Emily',
    accent: 'British',
    language: 'English (UK)',
    gender: 'female',
    description: 'Elegant, refined British female voice',
    elevenlabsVoiceId: 'LchlDJqwk16zfMCJ8s1',
    isPremium: false,
  },
  {
    id: 'en-uk-male-1',
    name: 'Oliver',
    accent: 'British',
    language: 'English (UK)',
    gender: 'male',
    description: 'Sophisticated British male voice',
    elevenlabsVoiceId: 'DyiL1BtAHjBTruYKdF1',
    isPremium: false,
  },
  {
    id: 'en-au-female-1',
    name: 'Charlotte',
    accent: 'Australian',
    language: 'English (Australia)',
    gender: 'female',
    description: 'Friendly, modern Australian female voice',
    elevenlabsVoiceId: 'IK4LgatcxD1S1QmB0F3',
    isPremium: false,
  },
  {
    id: 'en-au-male-1',
    name: 'Jack',
    accent: 'Australian',
    language: 'English (Australia)',
    gender: 'male',
    description: 'Casual, approachable Australian male voice',
    elevenlabsVoiceId: 'HwrFU1YjK1T1SnW0qL9',
    isPremium: false,
  },
  {
    id: 'en-za-female-1',
    name: 'Amara',
    accent: 'South African',
    language: 'English (South Africa)',
    gender: 'female',
    description: 'Modern South African female voice',
    elevenlabsVoiceId: 'MksfQ2WjK3V1RmY7tP5',
    isPremium: false,
  },
  {
    id: 'en-za-male-1',
    name: 'Thabo',
    accent: 'South African',
    language: 'English (South Africa)',
    gender: 'male',
    description: 'Authoritative South African male voice',
    elevenlabsVoiceId: 'NltgR3XkL4W2SnZ8uQ6',
    isPremium: false,
  },
  
  // European Languages
  {
    id: 'fr-fr-female-1',
    name: 'Sofia',
    accent: 'French',
    language: 'French',
    gender: 'female',
    description: 'Elegant French female voice',
    elevenlabsVoiceId: 'TX4fJ2YmK3V1RmY9tP7',
    isPremium: false,
  },
  {
    id: 'fr-fr-male-1',
    name: 'Pierre',
    accent: 'French',
    language: 'French',
    gender: 'male',
    description: 'Sophisticated French male voice',
    elevenlabsVoiceId: 'UY5gK3ZnL4W2SnA0uR8',
    isPremium: false,
  },
  {
    id: 'de-de-female-1',
    name: 'Lena',
    accent: 'German',
    language: 'German',
    gender: 'female',
    description: 'Clear German female voice',
    elevenlabsVoiceId: 'VZ6hL4AoM5X3ToB1vS9',
    isPremium: false,
  },
  {
    id: 'de-de-male-1',
    name: 'Hans',
    accent: 'German',
    language: 'German',
    gender: 'male',
    description: 'Professional German male voice',
    elevenlabsVoiceId: 'WA7iM5BpN6Y4UoC2wT0',
    isPremium: false,
  },
  {
    id: 'es-es-female-1',
    name: 'Carmen',
    accent: 'Spanish (Spain)',
    language: 'Spanish',
    gender: 'female',
    description: 'Melodic Spanish female voice',
    elevenlabsVoiceId: 'XB8jN6CqO7Z5VpD3xU1',
    isPremium: false,
  },
  {
    id: 'es-es-male-1',
    name: 'Carlos',
    accent: 'Spanish (Spain)',
    language: 'Spanish',
    gender: 'male',
    description: 'Warm Spanish male voice',
    elevenlabsVoiceId: 'YC9kO7DrP8A6WqE4yV2',
    isPremium: false,
  },
  {
    id: 'pt-br-female-1',
    name: 'Isabella',
    accent: 'Brazilian',
    language: 'Portuguese (Brazil)',
    gender: 'female',
    description: 'Friendly Brazilian female voice',
    elevenlabsVoiceId: 'ZD0lP8EsQ9B7XrF5zW3',
    isPremium: false,
  },
  {
    id: 'pt-br-male-1',
    name: 'Mateo',
    accent: 'Brazilian',
    language: 'Portuguese (Brazil)',
    gender: 'male',
    description: 'Modern Brazilian male voice',
    elevenlabsVoiceId: 'AE1mQ9FtR0C8YsG6aX4',
    isPremium: false,
  },
  {
    id: 'it-it-female-1',
    name: 'Bella',
    accent: 'Italian',
    language: 'Italian',
    gender: 'female',
    description: 'Expressive Italian female voice',
    elevenlabsVoiceId: 'BF2nR0GuS1D9ZtH7bY5',
    isPremium: false,
  },
  {
    id: 'it-it-male-1',
    name: 'Marco',
    accent: 'Italian',
    language: 'Italian',
    gender: 'male',
    description: 'Charismatic Italian male voice',
    elevenlabsVoiceId: 'CG3oS1HvT2E0AuI8cZ6',
    isPremium: false,
  },
  
  // African Languages
  {
    id: 'af-za-female-1',
    name: 'Lerato',
    accent: 'South African',
    language: 'Afrikaans',
    gender: 'female',
    description: 'Modern Afrikaans female voice',
    elevenlabsVoiceId: 'DH4pT2IwU3F1BdJ9dA7',
    isPremium: false,
  },
  {
    id: 'af-za-male-1',
    name: 'Daan',
    accent: 'South African',
    language: 'Afrikaans',
    gender: 'male',
    description: 'Friendly Afrikaans male voice',
    elevenlabsVoiceId: 'EI5qU3JxV4G2CeK0eB8',
    isPremium: false,
  },
  {
    id: 'sw-ke-female-1',
    name: 'Zahra',
    accent: 'Kenyan',
    language: 'Swahili',
    gender: 'female',
    description: 'Clear Swahili female voice',
    elevenlabsVoiceId: 'FJ6rV4KyW5H3DfL1fC9',
    isPremium: false,
  },
  {
    id: 'sw-ke-male-1',
    name: 'Juma',
    accent: 'Kenyan',
    language: 'Swahili',
    gender: 'male',
    description: 'Authoritative Swahili male voice',
    elevenlabsVoiceId: 'GK7sW5LzX6I4EgM2gD0',
    isPremium: false,
  },
  
  // Asian Languages
  {
    id: 'zh-cn-female-1',
    name: 'Mei',
    accent: 'Mandarin',
    language: 'Chinese (Simplified)',
    gender: 'female',
    description: 'Clear Mandarin female voice',
    elevenlabsVoiceId: 'HL8tX6MyY7J5FhN3hE1',
    isPremium: false,
  },
  {
    id: 'zh-cn-male-1',
    name: 'Wei',
    accent: 'Mandarin',
    language: 'Chinese (Simplified)',
    gender: 'male',
    description: 'Professional Mandarin male voice',
    elevenlabsVoiceId: 'IM9uY7NzZ8K6GiO4iF2',
    isPremium: false,
  },
  {
    id: 'ja-jp-female-1',
    name: 'Yuki',
    accent: 'Japanese',
    language: 'Japanese',
    gender: 'female',
    description: 'Soft Japanese female voice',
    elevenlabsVoiceId: 'JN0vA8OpA9L7HjP5jG3',
    isPremium: false,
  },
  {
    id: 'ja-jp-male-1',
    name: 'Kenji',
    accent: 'Japanese',
    language: 'Japanese',
    gender: 'male',
    description: 'Authoritative Japanese male voice',
    elevenlabsVoiceId: 'KN1wB9PqB0M8IkQ6kH4',
    isPremium: false,
  }
];
